# Autogenerated by infra_lib 0.0.1 on 2025-10-09T14:26:32+00:00 UTC.

import os
from infra_lib import InfraEnvironment, AWSInfraBuilder, AWSQueueConfig, AWSLambdaParameters

class StageInfra(AWSInfraBuilder):
    def build(self):
        """
        Build the infrastructure for stage environment and net8 stack.
        """
        # Create secrets first
        self.secrets_util.create_secrets()
        
        ## Add more infra